### ISSUE TITLE
clarification on TX and RX

### ISSUE THREAD

**Issue by supercazzola** [ok1cdj/FT817-satmode#1]
Clarification should be made in the program regarding the use of TX and RX nomenclature. What is TX on Radio may be RX on device. I recommend stating which pin of the 8 pin mini DIN the connections should be made to.

For example:
D2 connects to position 4 of the ACC port for master radio
D3 connects to position 5 of the ACC port for master radio
D4 connects to position 4 of the ACC port for the slave radio
D5 connects to position 5 of the ACC port for the slave radio

**Comment by ok1cdj** [comment]
Desc is in wiki now...
